version: '3.9'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./coverage:/project/coverage
    environment:
      - PORT=3000
      - REDIS_QUEUE_HOST=localhost
      - REDIS_QUEUE_PORT=6379
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379