name: Typescript Project Template CI

on: pull_request

jobs:
  ci:
    uses: organisation72/workflows/.github/workflows/typescript-ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
